/*
 * commands.h
 *
 *  Created on: Oct 30, 2023
 *      Author: dburger
 */

#ifndef INC_COMMANDS_H_
#define INC_COMMANDS_H_

#define GET_STATUS_ALL_STR "GET_STATUS_ALL\r"
#define GARAGE_PUMP_START_STR "GARAGE_PUMP_START\r"
#define GARAGE_PUMP_STOP_STR "GARAGE_PUMP_STOP\r"
#define FILL_LARGE_TANK_STR "FILL_LARGE_TANK\r"
#define FILL_SMALL_TANK_STR "FILL_SMALL_TANK\r"
#define FILL_NO_TANK_STR "FILL_NO_TANK\r"
#define SPRINKLER_START_STR "SPRINKLER_START\r"
#define SPRINKLER_STOP_STR "SPRINKLER_STOP\r"
#define HOSE_START_STR "HOSE_START\r"
#define HOSE_STOP_STR "HOSE_STOP\r"
//#define PRESSURE_PUMP_START_STR "PRESSURE_PUMP_START"
//#define PRESSURE_PUMP_STOP_STR "PRESSURE_PUMP_STOP"

typedef enum {
	GET_STATUS_ALL,
	GARAGE_PUMP_START,
	GARAGE_PUMP_STOP,
	FILL_LARGE_TANK,
	FILL_SMALL_TANK,
	FILL_NO_TANK,
	SPRINKLER_START,
	SPRINKLER_STOP,
	HOSE_START,
	HOSE_STOP,
	//PRESSURE_PUMP_START,
	//PRESSURE_PUMP_STOP,
	NONE
}Commands_t;

typedef struct {
    const char* cmdString;
    Commands_t cmdEnum;
} CommandMap_t;

static const CommandMap_t commandMap[] = {
	{GET_STATUS_ALL_STR, GET_STATUS_ALL},
	{GARAGE_PUMP_START_STR, GARAGE_PUMP_START},
	{GARAGE_PUMP_STOP_STR, GARAGE_PUMP_STOP},
	{FILL_LARGE_TANK_STR, FILL_LARGE_TANK},
	{FILL_SMALL_TANK_STR, FILL_SMALL_TANK},
	{FILL_NO_TANK_STR, FILL_NO_TANK},
	{SPRINKLER_START_STR, SPRINKLER_START},
	{SPRINKLER_STOP_STR, SPRINKLER_STOP},
	{HOSE_START_STR, HOSE_START},
	{HOSE_STOP_STR, HOSE_STOP},
    {NULL, NONE}
};

#endif /* INC_COMMANDS_H_ */
