/*
 * status.h
 *
 *  Created on: Nov 14, 2023
 *      Author: burge
 */

#ifndef INC_STATUS_H_
#define INC_STATUS_H_

#define GARAGE_PUMP_RUNNING_STR "GARAGE_PUMP_RUNNING"
#define GARAGE_PUMP_STOPPED_STR "GARAGE_PUMP_STOPPED"
#define LARGE_TANK_SELECTED_STR "LARGE_TANK_SELECTED"
#define SMALL_TANK_SELECTED_STR "SMALL_TANK_SELECTED"
#define NO_TANK_SELECTED_STR "NO_TANK_SELECTED"
#define SPRINKLER_RUNNING_STR "SPRINKLER_RUNNING"
#define SPRINKLER_STOPPED_STR "SPRINKLER_STOPPED"
#define HOSE_RUNNING_STR "HOSE_RUNNING"
#define HOSE_STOPPED_STR "HOSE_STOPPED"

typedef enum {
	GARAGE_PUMP_RUNNING,
	GARAGE_PUMP_STOPPED,
	LARGE_TANK_SELECTED,
	SMALL_TANK_SELECTED,
	NO_TANK_SELECTED,
	SPRINKLER_RUNNING,
	SPRINKLER_STOPPED,
	HOSE_RUNNING,
	HOSE_STOPPED,
	NONE
}Status_t;


#endif /* INC_STATUS_H_ */
